Update kernelbuilder.yml

diff --git a/.github/workflows/kernelbuilder.yml b/.github/workflows/kernelbuilder.yml
--- a/.github/workflows/kernelbuilder.yml
+++ b/.github/workflows/kernelbuilder.yml
@@ -39,9 +39,9 @@ jobs:
           uses: actions/cache@v4
           with:
             path: ~/.ccache
-            key: ${{ runner.os }}-ccache-${{ github.ref }}-${{ github.sha }}
+            key: ${{ runner.os }}-ccache-${{ github.ref_name }}-${{ github.sha }}
             restore-keys: |
-              ${{ runner.os }}-ccache-${{ github.ref }}-
+              ${{ runner.os }}-ccache-${{ github.ref_name }}-
               ${{ runner.os }}-ccache-
 
         - name: 'Validate workflow options'
@@ -68,40 +68,40 @@ jobs:
                 echo "--- All link-related workflow options seem to be valid! ---"
             fi
 
-        - name: 'Debloat the OS'
-          run: |
-            export DEBIAN_FRONTEND=noninteractive
-            echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
+        # - name: 'Debloat the OS'
+        #   run: |
+        #     export DEBIAN_FRONTEND=noninteractive
+        #     echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
 
-            echo "Storage spaces before debloat/clean-up:"
-            df -h
+        #     echo "Storage spaces before debloat/clean-up:"
+        #     df -h
 
-            sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup /opt/hostedtoolcache/CodeQL /usr/local/share/powershell /usr/share/swift || true
-            sudo docker image prune --all --force
-            echo "some directories deleted"
+        #     sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup /opt/hostedtoolcache/CodeQL /usr/local/share/powershell /usr/share/swift || true
+        #     sudo docker image prune --all --force
+        #     echo "some directories deleted"
 
-            # Remove large unwanted packages
-            sudo apt-get purge -y \
-                aria2 ansible azure-cli shellcheck rpm xorriso zsync \
-                esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
-                google-cloud-sdk imagemagick \
-                libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
-                mercurial apt-transport-https mono-complete libmysqlclient \
-                unixodbc-dev yarn chrpath libssl-dev libxft-dev \
-                libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
-                snmp pollinate libpq-dev postgresql-client powershell ruby-full \
-                sphinxsearch subversion mongodb-org microsoft-edge-stable || true
+        #     # Remove large unwanted packages
+        #     sudo apt-get purge -y \
+        #         aria2 ansible azure-cli shellcheck rpm xorriso zsync \
+        #         esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
+        #         google-cloud-sdk imagemagick \
+        #         libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
+        #         mercurial apt-transport-https mono-complete libmysqlclient \
+        #         unixodbc-dev yarn chrpath libssl-dev libxft-dev \
+        #         libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
+        #         snmp pollinate libpq-dev postgresql-client powershell ruby-full \
+        #         sphinxsearch subversion mongodb-org microsoft-edge-stable || true
 
-            # Regex-based purges (for bulk families like mysql, php, dotnet)
-            sudo apt-get purge -y $(dpkg-query -W -f='${binary:Package}\n' | grep -E '^mysql|^php|^dotnet') || true
+        #     # Regex-based purges (for bulk families like mysql, php, dotnet)
+        #     sudo apt-get purge -y $(dpkg-query -W -f='${binary:Package}\n' | grep -E '^mysql|^php|^dotnet') || true
 
-            # Clean up
-            sudo apt-get autoremove -y
-            sudo apt-get autoclean -y
-            echo "some packages purged"
+        #     # Clean up
+        #     sudo apt-get autoremove -y
+        #     sudo apt-get autoclean -y
+        #     echo "some packages purged"
 
-            echo "Storage spaces after debloat/clean-up:"
-            df -h
+        #     echo "Storage spaces after debloat/clean-up:"
+        #     df -h
 
         - name: 'Setup dependencies and environment'
           run: |
@@ -164,6 +164,7 @@ jobs:
         - name: Configure ccache
           run: |
             ccache -M 5G
+            ccache -o compression=true
             ccache -z
 
         - name: 'Clone kernel source'
